### PR TITLE
Added links for all groups

### PR DESCRIPTION
**Pull request by StrangeWill**
Links for everyone!

### CODE REVIEW

**Comment by keathley** [comment]
This looks good to me.  I hadn't thought about these needing to be approved organizations.  Right now what I'm thinking is that we should go ahead and merge this and start talking to these groups to make sure they have a code of conduct.  If they don't want to do that then we can remove them.  Anyone else have thoughts?

**Comment by StrangeWill** [comment]
I think they should stay synced, I'm even tempted to remove them sooner rather than later if we're going to do that.

**Comment by vendion** [comment]
I'm fine with requiring a Code of Conduct for them to be listed on the site (http://chadev.github.io/groups/) but I don't think that should limit us from promoting them during lunch.  So that others will know about about the different groups.  If we do go ahead with requiring a CoC to be on the slides we should work that out before merging this is.

**Comment by keathley** [comment]
I'm closing this for now.  The discussion of inclusion and Code of Conduct has moved here: https://github.com/chadev/chadev.github.io/pull/84

**Pull request merged**
